"use strict";

var _core = _interopRequireDefault(require('./../../vendor.js')(1));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

_core["default"].page({
  data: {},
  props: {
    goods: {
      type: Object,
      "default": {}
    }
  }
}, {info: {"components":{"i-input":{"path":"./../../vendor/iview/input/index"},"i-card":{"path":"./../../vendor/iview/card/index"},"van-search":{"path":"./../../vendor/vant/search/index"},"van-toast":{"path":"./../../vendor/vant/toast/index"},"van-grid":{"path":"./../../vendor/vant/grid/index"},"van-grid-item":{"path":"./../../vendor/vant/grid-item/index"}},"on":{}}, handlers: {}, models: {}, refs: undefined }, {info: {"components":{"i-input":{"path":"./../../vendor/iview/input/index"},"i-card":{"path":"./../../vendor/iview/card/index"},"van-search":{"path":"./../../vendor/vant/search/index"},"van-toast":{"path":"./../../vendor/vant/toast/index"},"van-grid":{"path":"./../../vendor/vant/grid/index"},"van-grid-item":{"path":"./../../vendor/vant/grid-item/index"}},"on":{}}, handlers: {}, models: {}, refs: undefined }, {info: {"components":{"i-input":{"path":"./../../vendor/iview/input/index"},"i-card":{"path":"./../../vendor/iview/card/index"},"van-search":{"path":"./../../vendor/vant/search/index"},"van-toast":{"path":"./../../vendor/vant/toast/index"},"van-grid":{"path":"./../../vendor/vant/grid/index"},"van-grid-item":{"path":"./../../vendor/vant/grid-item/index"}},"on":{}}, handlers: {}, models: {}, refs: undefined }, {info: {"components":{"i-input":{"path":"./../../vendor/iview/input/index"},"i-card":{"path":"./../../vendor/iview/card/index"},"van-search":{"path":"./../../vendor/vant/search/index"},"van-toast":{"path":"./../../vendor/vant/toast/index"},"van-grid":{"path":"./../../vendor/vant/grid/index"},"van-grid-item":{"path":"./../../vendor/vant/grid-item/index"}},"on":{}}, handlers: {}, models: {}, refs: undefined }, {info: {"components":{"i-input":{"path":"./../../vendor/iview/input/index"},"i-card":{"path":"./../../vendor/iview/card/index"},"van-search":{"path":"./../../vendor/vant/search/index"},"van-toast":{"path":"./../../vendor/vant/toast/index"},"van-grid":{"path":"./../../vendor/vant/grid/index"},"van-grid-item":{"path":"./../../vendor/vant/grid-item/index"}},"on":{}}, handlers: {}, models: {}, refs: undefined }, {info: {"components":{"i-input":{"path":"./../../vendor/iview/input/index"},"i-card":{"path":"./../../vendor/iview/card/index"},"van-search":{"path":"./../../vendor/vant/search/index"},"van-toast":{"path":"./../../vendor/vant/toast/index"},"van-grid":{"path":"./../../vendor/vant/grid/index"},"van-grid-item":{"path":"./../../vendor/vant/grid-item/index"}},"on":{}}, handlers: {}, models: {}, refs: undefined }, {info: {"components":{"i-input":{"path":"./../../vendor/iview/input/index"},"i-card":{"path":"./../../vendor/iview/card/index"},"van-search":{"path":"./../../vendor/vant/search/index"},"van-toast":{"path":"./../../vendor/vant/toast/index"},"van-grid":{"path":"./../../vendor/vant/grid/index"},"van-grid-item":{"path":"./../../vendor/vant/grid-item/index"}},"on":{}}, handlers: {}, models: {}, refs: undefined });